# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCQjwabVVWy5vBeXyrGlR_woznnVgcFn
"""

balance= 500
print("Welcome to Northern Frock")
mdp= 1234
user_mdp=int(input("Enter your password:  "))
nb_attempts=1
while user_mdp!=mdp and nb_attempts< 3:
    user_mdp=int(input("Enter your password:  "))
    nb_attempts=nb_attempts+1

if user_mdp==mdp:
  while True:
    print("\n" "1-Display balance","\n" "2-Withdraw funds","\n" "3-Deposit funds", "\n" "9-Return card")
    chosen_num=int(input("Select an operation: "))
    if chosen_num ==1:
        print("The current balance is:",'£{:,.2f}'.format(balance))
    elif chosen_num== 2:
        print("Please select withdrawal ammount: ","\n","1-10","\n","2-20","\n","3-40","\n","4-60","\n","5-80","\n","6-100","\n", "7-Other amount,""\n","8-Return to main menu")
        chosen_amount=int(input("Select the amount:   "))
        if chosen_amount==1:
            print("The amount of £10 has been withdrawn")
            balance=balance-10
            print("The current balance is:",'£{:,.2f}'.format(balance))
        elif chosen_amount==2:
            print("The amount of £20 has been withdrawn")
            balance=balance-20
            print("The current balance is:",'£{:,.2f}'.format(balance))
        elif chosen_amount==3:
            print("The amount of £40 has been withdrawn")
            balance=balance-40
            print("The current balance is:",'£{:,.2f}'.format(balance))
        elif chosen_amount==4:
            print("The amount of £60 has been withdrawn")
            balance=balance-60
            print("The current balance is:",'£{:,.2f}'.format(balance))

        elif chosen_amount==5:
            print("The amount of £80 has been withdrawn")
            balance=balance-80
            print("The current balance is:",'£{:,.2f}'.format(balance))
        elif chosen_amount==6:
            print("The amount of £100 has been withdrawn")
            balance=balance-100
            print("The current balance is:",'£{:,.2f}'.format(balance))
        elif chosen_amount==7:
            amount=int(input("Enter an other amount:   "))
            if amount % 10==0 and amount<=balance:
                print("The money has been withdrawn")
                balance=balance-amount
                print("The current balance is:",'£{:,.2f}'.format(balance))
            else :
              print("Error: The amount should be a multiple of 10 and less than balance")
    elif chosen_num==3:
        print("1-Enter an amount to deposit" "\n" "2-Return to main menu ")
        selected_num=int(input("Select an operation: "))
        if selected_num==1:
            dep=int(input("Enter the amount to deposit: "))
            print("The amount had been successfully added to your balance")
            balance=balance+dep
            print("The current balance is:",'£{:,.2f}'.format(balance))
    elif chosen_num==9:
        print("Good bye")
        break
    else:
        print("Error: Invalid operation")
else:
    print("Please come back later")